### ISSUE TITLE
WBbt:0005780, wrong 'is_a' relationship

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/c-elegans-gross-anatomy-ontology#33]
Hi Wormbase team,

I would like to draw your attention to this error:

[Term]
id: WBbt:0005780
name: non-striated muscle
is_a: WBbt:0003675 ! muscle cell => a muscle is not a cell

Kind regards,

Anne Niknejad
bgee.org curator
UNIL University of Lausanne

**Comment by raymond91125** [comment]
In C. elegnas (perhaps most nematodes), muscles are generally individualized as cells rather than tissues. See WormAtlas <https://www.wormatlas.org/glossary/sglossary.htm#striatedmuscle>. I hope this does not cause problems for you.

**Comment by chris-grove** [comment]
@raymond91125 
I think we could address this issue by formally changing the name of the term "non-striated muscle" to "non-striated muscle cell" and define it as such (a cell). Likewise this could be done for all of the descendant terms.

**Comment by raymond91125** [comment]
Sure. The names without "cell" are in-line with WormAtlas usage thus should be kept in synonyms.

**Comment by matentzn** [comment]
I would generally strongly advice against this - now our species specific anatomy classes are being used outside our own mods, we should never migrate a term to mean something else just because the labels look similar. Unless muscle cell and muscle really mean the same, it would be better if you created new terms instead of renaming existing ones..

**Comment by chris-grove** [comment]
@matentzn 
The issue here is that in C. elegans, because it' such a small animal, it's pretty much true that each 'muscle' in the worm is an individual muscle cell, so they are essentially synonymous, although I would very much prefer to be explicit and label it as such ("a cell"). Here's a screenshot of the term and some of its descendants:
<img width="1107" alt="Screen Shot 2021-06-29 at 9 39 58 AM" src="https://user-images.githubusercontent.com/611382/123807917-4781b200-d8be-11eb-98e3-07344802b58f.png">
So "non-striated muscle" is a subclass of "muscle cell" essentially because the meaning is already "non-striated muscle cell" bit it isn't obvious the way the labels are constructed. I'm not suggesting changing the meaning of any existing term. I'm only suggesting that the labels are updated to properly reflect the actual meaning.
