### ISSUE TITLE
'amphid process' part_of AWC issue

### ISSUE THREAD

**Issue by chris-grove** [obophenotype/c-elegans-gross-anatomy-ontology#8]
@raymond91125 
I've run into an issue with a recent help desk inquiry (that you have already answered) regarding finding genes expressed in the AWC neuron. The issue is that the anatomy term "amphid process" is considered "part of" the AWC neuron, and therefore any genes annotated to "amphid process" in any context (in any amphid neuron) are being returned by WOBr as being expressed in AWC, which isn't necessarily correct. In fact, on the "amphid process" page:

https://wormbase.org/species/all/anatomy_term/WBbt:0005393#041--10

the "Associations" widget displays five genes annotated to "amphid process", three of which (hda-4, pam-1, and arrd-6) have no annotations to AWC, AWCL, or AWCR, yet these three genes will always be returned as expressed in AWC with the current logic.

I would like to suggest that we make "amphid process" only a "part of" the "amphid neuron" term. We could create an "AWC amphid process" - "part of" - "AWC" axiom if we wanted, but I think the current construction will return incorrect results in WOBr.

**Comment by draciti** [comment]
@raymond91125, I encountered a similar case for ADFL/R. 
https://wormbase.org/tools/ontology_browser/show_genes?focusTermName=ADFL&focusTermId=WBbt:0004003
The number of genes directly annotated is 90 and the ones direct+inferred is 95 because it includes annotations to amphid process. As Chris mentioned above, it would be better to have 'amphid process' 'part  of' 'amphid neuron'. Thanks

**Comment by raymond91125** [comment]
Thanks for reminder.
